version: '{build}'
image: Visual Studio 2019
configuration: Release
build_script:  
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  name: production
  api_key:
    secure: AsSRKDskbEn9IqPhq7b5GklNgD/7dmjxsIslODJDhLW0FdsDHiD2I6hIWR+Jjm8i
  on:
    branch: master
    appveyor_repo_tag: true